---
title: "Final Overview"
output: pdf_document
---

For the final project, you will be splitting into groups to work on one of three possible projects. The end goal is a paper and presentation that will take place during the last week (maybe last two weeks) of the semester. You will be graded on your application of lessons we have learned throughout the semester as well as your ability to explain your methods both in the paper and during the presentation.

You can select one of three projects to work on for the final. The first project involves predicting whether late NBA star Kobe Bryant makes or misses a shot based on several factors of the shot, such as distance from basket, type of shot, and opponent. The second project involves predicting whether a shelter animal has a positive (adoption, returned to original owner) or negative (euthanized, transferred to other shelter) outcome based on information on the animal. The third project will involve predicting housing prices based on different aspects and qualities of the house and neighborhood.

An outline of the paper will be provided on Blackboard. Your presentation should be a general overview over what your goals were, what you did, and the conclusions you can make from your project. The presentation should be 10-15 minutes long. There is no set minimum for the paper. Presentations will be on the 14th week of class. Everyone's power point and paper will be due before the first presentations. You will also be asked to grade the contributions of all of your group members; this will also be due before the presentations.